name: countries_navigator
description: Countries for dummies

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# `flutter pub outdated`.
dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_smart_retry: ^1.3.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.3
  get_it: ^7.2.0
  go_router: ^4.2.7
  http: ^0.13.5
  internet_connection_checker_plus: ^1.0.1
  logger: ^1.1.0
  path_provider: ^2.0.11
  pdf: ^3.8.2
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.3
  flutter_native_splash: ^2.2.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
